# Generated by Django 4.1.4 on 2023-10-02 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='email',
            new_name='uemail',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='first_name',
            new_name='ufirstname',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='last_name',
            new_name='ulastname',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='password',
            new_name='upassword',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='username',
            new_name='uusername',
        ),
    ]
