# Generated by Django 4.1.4 on 2023-10-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ufirstname', models.CharField(max_length=100)),
                ('ulastname', models.CharField(max_length=100)),
                ('uusername', models.CharField(max_length=50, unique=True)),
                ('uemail', models.EmailField(max_length=254, unique=True)),
                ('upassword', models.CharField(max_length=100)),
            ],
        ),
    ]
