# Generated by Django 4.1.4 on 2023-10-02 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
