# Generated by Django 4.1.4 on 2023-11-05 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_therapistnew'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Therapist',
        ),
        migrations.DeleteModel(
            name='TherapistNew',
        ),
    ]
