# Generated by Django 4.1.4 on 2023-11-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_appointment_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_therapist',
            field=models.BooleanField(default=False),
        ),
    ]
