# Generated by Django 4.1.4 on 2023-11-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_appointment_is_therapist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_therapist',
            field=models.BooleanField(default=False),
        ),
    ]
