# Generated by Django 4.1.4 on 2023-11-26 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
