# Generated by Django 4.1.4 on 2023-11-26 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
