# Generated by Django 4.1.4 on 2024-01-23 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_timeslot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
