# Generated by Django 4.1.4 on 2024-02-05 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_timeslot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
