# Generated by Django 4.1.4 on 2024-02-19 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_timeslotnew_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslotnew',
            name='therapist',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='TimeSlotNew',
        ),
    ]
