# Generated by Django 4.1.4 on 2024-02-19 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0035_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
