# Generated by Django 4.1.4 on 2024-03-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0040_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status_change_notification',
            field=models.BooleanField(default=False),
        ),
    ]
