# Generated by Django 4.1.4 on 2024-03-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0044_appointment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
