# Generated by Django 4.1.4 on 2024-03-22 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0048_order_payment_status_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
