# Generated by Django 4.1.4 on 2024-03-22 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0049_alter_order_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status_change_notification',
        ),
    ]
