# Generated by Django 4.1.4 on 2024-03-22 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0050_remove_order_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
