# Generated by Django 4.1.4 on 2024-04-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0053_rename_paid_by_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default_product_image.jpg', upload_to='product_images/'),
        ),
    ]
