# Generated by Django 4.1.4 on 2024-04-06 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0055_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
