# Generated by Django 4.2.11 on 2024-04-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0058_mentalhealthstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentalhealthstatus',
            name='energy_level',
            field=models.CharField(choices=[('High', 'High'), ('Moderate', 'Moderate'), ('Low', 'Low')], default='Moderate', max_length=50),
        ),
        migrations.AddField(
            model_name='mentalhealthstatus',
            name='mood',
            field=models.CharField(choices=[('Happy', 'Happy'), ('Neutral', 'Neutral'), ('Sad', 'Sad')], default='Neutral', max_length=50),
        ),
        migrations.AddField(
            model_name='mentalhealthstatus',
            name='sleep_quality',
            field=models.CharField(choices=[('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], default='Good', max_length=50),
        ),
        migrations.AddField(
            model_name='mentalhealthstatus',
            name='stress_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], default='Low', max_length=50),
        ),
        migrations.AddField(
            model_name='mentalhealthstatus',
            name='thoughts',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='mentalhealthstatus',
            name='status',
            field=models.CharField(choices=[('Feeling Anxious', 'Feeling Anxious'), ('Feeling Depressed', 'Feeling Depressed'), ('Feeling Stressed', 'Feeling Stressed')], default='Feeling Anxious', max_length=255),
        ),
    ]
